#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.
# Check if IP address argument is passed, otherwise show usage.
# Ping the IP address 5 times.

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
