#!/usr/bin/env bash
# Set up PID file for the script
echo $$ > /var/run/myscript.pid

# Handle the SIGTERM signal
trap 'echo "Terminating script..."; rm -rf /var/run/myscript.pid; exit' SIGTERM

# Handle the SIGINT signal
trap 'echo "Interrupt signal received!"' SIGINT

# Handle the SIGQUIT signal
trap 'echo "Quitting script..."; rm -rf /var/run/myscript.pid; exit' SIGQUIT

# Loop forever and print a message every 2 seconds
while :
do
    echo "To infinity and beyond"
    sleep 2
done
