#!/usr/bin/env bash
# Script to manage my_process

PIDFILE=/var/run/my_process.pid

# Function to start my_process
start() {
    ./manage_my_process &   # Run my_process in background
    echo "$!" > "$PIDFILE"  # Save the process ID to a file
}

# Function to stop my_process
stop() {
    sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"  # Send a signal to stop the process and remove the PID file
}

# Check the first argument and call the appropriate function
case "$1" in 
    start)
       start
       echo "my_process started"  # Print a message indicating the process was started
       ;;
    stop)
       stop
       echo "my_process stopped"  # Print a message indicating the process was stopped
       ;;
    restart)
       stop
       start
       echo "my_process restarted"  # Print a message indicating the process was restarted
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"  # Print a usage message if the argument is not recognized
esac

exit 0  # Exit the script with a status of 0 (success)
