#!/usr/bin/env bash
# This script extracts the IP address and HTTP status code from an Apache access log file.
# Use awk to print the first (IP address) and ninth (HTTP status code) columns of the log file.
awk '{ print $1, $9}' apache-access.log
