#!/usr/bin/env bash
# Set the initial value of the counter to 1
counter=1

# While the counter is less than or equal to 10, execute the loop body
while [ $counter -le 10 ]
do
    # Display the message "Best School"
    echo "Best School"

    # Increment the counter by 1
    ((counter++))
done
