#!/usr/bin/env bash

# Set counter to 1
counter=1

# Loop 10 times and display "Best School"
while [ $counter -le 10 ]
do
    echo "Best School"
    
    # Print "Hi" on the 9th iteration
    if [[ "$counter" == '9' ]]
    then
        echo "Hi"
    fi
    
    # Increment the counter
    ((counter++))
done
