#!/usr/bin/env bash
# This Bash script prints "Best School" 10 times with some variations

counter=1
while [ $counter -le 10 ]
do
    if [[ $counter == '4' ]]
    then
        # Print "bad luck" on the 4th iteration
        echo "bad luck"
    elif [[ $counter == '8' ]]
    then
        # Print "good luck" on the 8th iteration
        echo "good luck"
    else
        # Print "Best School" on all other iterations
        echo "Best School"
    fi
    ((counter++))
done
