#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with "bad luck" messages for certain values.
# Set the initial counter to 1.
counter=1
# While the counter is less than or equal to 20, loop through the following statements.
while [ $counter -le 20 ]
do
    # Use a case statement to check the value of the counter.
    case $counter in
        # If the counter is 4, display a "bad luck" message from China.
        "4")
            echo "$counter"
            echo "China - bad luck"
            ;;
        # If the counter is 9, display a "bad luck" message from Japan.
        "9")
            echo "$counter"
            echo "Japan - bad luck"
            ;;
        # If the counter is 17, display a "bad luck" message from Italy.
        "17")
            echo "$counter"
            echo "Italy - bad luck"
            ;;
        # For all other values of the counter, simply display the number.
        *)
            echo "$counter"
            ;;
    esac

    # Increment the counter by 1 after each iteration.
    ((counter++))
done
