#!/usr/bin/env bash
# Script: list_files.sh
# Description: List files in the current directory with names
# containing a dash, displaying only the part of the name after the dash

for file in *
do
    # Use the 'cut' command to extract the part of the file name
    # after the first dash and display it on the console
    echo "$file" | cut -f 2 -d '-'
done
