#!/usr/bin/env bash
# Check if the "school" file exists
FILE="school"
if [[ -e "$FILE" ]]
then
    # Print a message if the file exists
    echo "File '$FILE' exists"
    if [ -s "$FILE" ]
    then
        # Print a message if the file is not empty
        echo "File '$FILE' is not empty"
    else
        # Print a message if the file is empty
        echo "File '$FILE' is empty"
    fi
    if [ -f "$FILE" ]
    then
        # Print a message if the file is a regular file
        echo "File '$FILE' is a regular file"
    fi
else
    # Print a message if the file does not exist
    echo "File '$FILE' does not exist"
fi
