#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
# Copy the current hosts file and save as ~/hosts.new

cp /etc/hosts ~/hosts.new
# Change the localhost resolution from 127.0.0.1 to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
# Set the IP address of facebook.com to 8.8.8.8
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
